-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [add_ten]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace add_ten

/-- [add_ten::add_ten]:
    Source: 'add_ten/src/lib.rs', lines 1:0-3:1
    Visibility: public -/
def add_ten (x : Std.U32) : Result Std.U32 := do
  x + 10#u32

/-- `add_ten` succeeds whenever `x + 10` does not overflow `U32`, and on
    success it returns exactly `x + 10`. -/
theorem add_ten.spec (x : Std.U32) (h : x.val + 10 ≤ Std.U32.max) :
    add_ten x ⦃ res => res.val = x.val + 10 ⦄ := by
  unfold add_ten
  step as ⟨ res, hres ⟩
  exact hres

/-- Hypothesis form: whenever `add_ten` succeeds, the result is exactly the
    mathematical sum (no silent wraparound). -/
theorem add_ten.spec' (x y : Std.U32) (h : add_ten x = ok y) :
    y.val = x.val + 10 := by
  unfold add_ten at h
  have he := UScalar.add_equiv x (10#u32)
  rw [h] at he
  exact he.2.1

/-- `add_ten` fails exactly when the addition would overflow `U32`. -/
theorem add_ten.spec_overflow (x : Std.U32) (h : Std.U32.max < x.val + 10) :
    ¬ ∃ y, add_ten x = ok y := by
  unfold add_ten
  rintro ⟨y, hy⟩
  have he := UScalar.add_equiv x (10#u32)
  rw [hy] at he
  scalar_tac

end add_ten
