/-
Copyright (c) 2026 Iulian Simion. All rights reserved.
Released under the 3-Clause BSD License as described in the file LICENSE.
Authors: Iulian Simion, assisted by Claude (Anthropic) and Gemini (Google)
-/
-- THE DEFINITIONS UP TO `Specs & Formal verification` WERE GENERATED BY AENEAS
-- [add_ten]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-!
Aeneas writes the two options above at the top of each generated file. Each
sets a limit at which Lean stops with an error instead of continuing.

* `maxHeartbeats` limits the work that Lean may do on a single command, such as
  a definition or a theorem. The work is measured in thousands of small memory
  allocations, called heartbeats, so the limit does not depend on the speed of
  the computer. The default is `200000`, and `0` removes the limit. A command
  that exceeds it fails with the error `(deterministic) timeout`.
* `maxRecDepth` limits the depth of nested recursive calls in many procedures
  of Lean, such as elaboration and `simp`. The default is `512`. A command that
  exceeds it fails with the error `maximum recursion depth has been reached`.

Aeneas raises the two limits to `1000000` and `2048`, since large generated
definitions can exceed the defaults. The comments above the options name the
command-line options of Aeneas that change these values.
-/

/-!
# Addition with overflow

The Rust function

```rust
pub fn add_ten(x: u32) -> u32 {
    x + 10
}
```

adds `10` to an unsigned 32-bit integer. The type `u32` has the values
`0, 1, …, 2 ^ 32 - 1`. When `x + 10` exceeds `2 ^ 32 - 1`, the addition
**overflows**. By default, a Rust program compiled in debug mode then panics,
and a program compiled in release mode computes the sum modulo `2 ^ 32`. Aeneas
translates an arithmetic operation that can overflow into an operation that
fails on overflow.

The definitions above the comment `Specs & Formal verification` were generated
by Aeneas from `add_ten/src/lib.rs`. The specifications and proofs below it
are not part of the translation.

## The generated definition

* The type `Std.U32` is the Lean model of `u32`. A term `x : Std.U32` has a
  value `x.val : ℕ`, and `x.val ≤ Std.U32.max`, where
  `Std.U32.max = 2 ^ 32 - 1`.
* The notation `10#u32` denotes the constant `10` of type `Std.U32`.
* The sum `x + 10#u32` has the type `Result Std.U32`. It is `ok z` with
  `z.val = x.val + 10` when this sum is at most `Std.U32.max`, and it fails
  otherwise.
* The comment above the definition records the name of the Rust function, its
  position in the source file, and its visibility.
-/

namespace add_ten

/-- [add_ten::add_ten]:
    Source: 'add_ten/src/lib.rs', lines 1:0-3:1
    Visibility: public -/
def add_ten (x : Std.U32) : Result Std.U32 := do
  x + 10#u32

/-!
## Specifications

A specification of a function that returns a `Result` describes its result. The
notation

  `f x ⦃ res => P res ⦄`

states that `f x` is `ok res` for some `res` with `P res`. In the braces, `res`
is a name for the result of `f x`, and `P res`, a proposition about this result,
is the **postcondition**. In `add_ten.spec` below, the braces contain
`res => res.val = x.val + 10`. As with `fun res => …`, the name `res` is bound,
and any other name can be used instead.

The notation stands for `WP.spec (f x) (fun res => P res)`, where `WP` is a
namespace of the Aeneas library. The name stands for **weakest precondition**, a
notion of program verification introduced by Dijkstra in 1975. It is a
condition on the input that holds exactly when the program terminates with a
result that satisfies the postcondition. The proposition `WP.spec (ok v) P` is
`P v`, and `WP.spec (fail e) P` and `WP.spec div P` are `False`.

The specification `add_ten.spec` has the precondition
`x.val + 10 ≤ Std.U32.max`, which excludes overflow. Its proof uses the tactic
`step`. On a goal `e ⦃ … ⦄`, where `e` is a function call or an operation such as
`x + 10#u32`, the tactic `step` finds a specification of `e` among the theorems
tagged `@[step]`, tries to prove its precondition, which it
leaves as a goal if it cannot, and introduces the
result of `e` together with its postcondition. The clause `as ⟨ res, hres ⟩`
names the result and its postcondition. Here the specification of the addition
gives `hres : res.val = x.val + 10`.
-/

----------------------------------------------------------------------------------------------------
-- Specs & Formal verification
----------------------------------------------------------------------------------------------------

/-- `add_ten` succeeds whenever `x + 10` does not overflow `U32`, and on
    success it returns exactly `x + 10`. -/
theorem add_ten.spec (x : Std.U32) (h : x.val + 10 ≤ Std.U32.max) :
    add_ten x ⦃ res => res.val = x.val + 10 ⦄ := by
  unfold add_ten
  step as ⟨ res, hres ⟩
  exact hres

/-!
The second theorem has the hypothesis form: whenever `add_ten x` is `ok y`, the
value of `y` is `x.val + 10`. It needs no precondition, and it states nothing
about the inputs for which `add_ten` fails.

The library lemma `UScalar.add_equiv x y` describes the outcomes of `x + y`, for
unsigned machine integers of any width, by a `match` on the three constructors
of `Result`:

* if `x + y` is `ok z`, then three facts hold: `x.val + y.val < 2 ^ ty.numBits`,
  where `ty.numBits` is the number of bits, here `32`; `z.val = x.val + y.val`;
  and `z.bv = x.bv + y.bv`, the same equation for the bit vectors;
* if `x + y` is `fail e`, then the sum is out of bounds;
* if `x + y` is `div`, the lemma gives the proposition `⊥`, which is `False`,
  so this case does not occur. The result `div` arises only from computations
  that may not terminate, such as loops, and an addition always terminates.
  The function `add_ten` contains no loop and no recursive call, so it is never
  `div` either.

After `unfold add_ten at h`, the hypothesis is `h : x + 10#u32 = ok y`.
Rewriting with it turns the argument of the `match` into `ok y`. The pattern of
`obtain` then reduces the `match` to its first case and takes out the second
fact. In the pattern `⟨-, hval, -⟩`, the symbol `-` drops
the first and the third fact from the context.
-/

/-- Hypothesis form: whenever `add_ten` succeeds, the result is exactly the
    mathematical sum (no silent wraparound). -/
theorem add_ten.spec' (x y : Std.U32) (h : add_ten x = ok y) :
    y.val = x.val + 10 := by
  unfold add_ten at h
  have he := UScalar.add_equiv x (10#u32)
  rw [h] at he
  obtain ⟨-, hval, -⟩ := he
  exact hval

/-!
The third theorem states when the function fails: if `x.val + 10` exceeds
`Std.U32.max`, then `add_ten x` is not `ok y` for any `y`. The tactic
`scalar_tac` proves arithmetic goals about machine integers. It adds the bounds
of the machine integers in the context as hypotheses, such as
`x.val ≤ Std.U32.max`, simplifies the goal and the hypotheses, and finishes
with `omega`.
-/

/-- `add_ten` fails when the addition would overflow `U32`: there is then no
    `y` with `add_ten x = ok y`. -/
theorem add_ten.spec_overflow (x : Std.U32) (h : Std.U32.max < x.val + 10) :
    ¬ ∃ y, add_ten x = ok y := by
  unfold add_ten
  rintro ⟨y, hy⟩
  have he := UScalar.add_equiv x (10#u32)
  rw [hy] at he
  scalar_tac

end add_ten
