-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [affine_cipher]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace affine_cipher

/-- [affine_cipher::affine_encrypt]: loop body 0:
    Source: 'affine_cipher/src/lib.rs', lines 3:4-6:5
    Visibility: public -/
@[rust_loop_body]
def affine_encrypt_loop.body
  {N : Std.Usize} (a : Std.U8) (b : Std.U8) (data : Array Std.U8 N)
  (i : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 N) × Std.Usize) (Array Std.U8 N))
  := do
  if i < N
  then
    let i1 ← Array.index_usize data i
    let i2 ← lift (core.num.U8.wrapping_mul i1 a)
    let i3 ← lift (core.num.U8.wrapping_add i2 b)
    let a1 ← Array.update data i i3
    let i4 ← i + 1#usize
    ok (cont (a1, i4))
  else ok (done data)

/-- [affine_cipher::affine_encrypt]: loop 0:
    Source: 'affine_cipher/src/lib.rs', lines 3:4-6:5
    Visibility: public -/
@[rust_loop]
def affine_encrypt_loop
  {N : Std.Usize} (data : Array Std.U8 N) (a : Std.U8) (b : Std.U8)
  (i : Std.Usize) :
  Result (Array Std.U8 N)
  := do
  loop
    (fun (data1, i1) => affine_encrypt_loop.body a b data1 i1)
    (data, i)

/-- [affine_cipher::affine_encrypt]:
    Source: 'affine_cipher/src/lib.rs', lines 1:0-8:1
    Visibility: public -/
@[reducible]
def affine_encrypt
  {N : Std.Usize} (data : Array Std.U8 N) (a : Std.U8) (b : Std.U8) :
  Result (Array Std.U8 N)
  := do
  affine_encrypt_loop data a b 0#usize


----------------------------------------------------------------------------------------------------
-- Specs & Formal verification: TODO
----------------------------------------------------------------------------------------------------


end affine_cipher
