-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [enums]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace enums

/-- [enums::Light]
    Source: 'enums/src/lib.rs', lines 1:0-1:37
    Visibility: public -/
@[discriminant isize]
inductive Light where
| Red : Light
| Green : Light
| Yellow : Light

/-- [enums::next_light]:
    Source: 'enums/src/lib.rs', lines 3:0-9:1
    Visibility: public -/
def next_light (current : Light) : Result Light := do
  match current with
  | Light.Red => ok Light.Green
  | Light.Green => ok Light.Yellow
  | Light.Yellow => ok Light.Red


----------------------------------------------------------------------------------------------------
-- Specs & Formal verification
----------------------------------------------------------------------------------------------------


/- Period-3 cycle. The interesting semantic property of a traffic light:
three transitions return you to where you started.-/
theorem next_light_cycle (c : Light) :
    (do let a ← next_light c
        let b ← next_light a
        next_light b) = ok c := by
  cases c <;> rfl


/- No fixed point. The light always actually changes — a cheap safety property
that rules out a whole class of typo bugs (Light::Green => Light::Green).-/
theorem next_light_ne (c : Light) : ∃ c', next_light c = ok c' ∧ c' ≠ c := by
  cases c <;> simp [next_light]


end enums
