/-
Copyright (c) 2026 Iulian Simion. All rights reserved.
Released under the 3-Clause BSD License as described in the file LICENSE.
Authors: Iulian Simion, assisted by Claude (Anthropic) and Gemini (Google)
-/
-- THE DEFINITIONS UP TO `Specs & Formal verification` WERE GENERATED BY AENEAS
-- [error_codes]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-!
# Error codes

The crate is adapted from the presentation "Rust for Linux: Code Documentation &
Tests" of the Linux Foundation mentorship series. The type `ErrorCode` wraps a
Linux kernel error code. The kernel returns errors as negative numbers, such as
`-EPERM` or `-ENOMEM`; the type `ErrorCode` stores the positive number, from `1`
to `MAX_ERROR_CODE = 4095`. The bound `4095` is the kernel's constant
`MAX_ERRNO`, which lets a function return either a valid pointer or an error
code in the same value:

```rust
pub const MAX_ERROR_CODE: i32 = 4095;

pub struct ErrorCode {
    value: i32,
}

impl ErrorCode {
    pub fn from_code(code: i32) -> Result<Self, ()> {
        if code <= 0 || code > MAX_ERROR_CODE {
            return Err(());
        }
        Ok(ErrorCode { value: code })
    }

    pub fn to_code(self) -> i32 {
        self.value
    }
}
```

The field `value` is private: it is visible only in the module that declares
it and in the modules inside it. Here that module is the root of the crate, so
code in other crates can construct an `ErrorCode` only through `from_code`,
which accepts only codes between `1` and `MAX_ERROR_CODE`. Every `ErrorCode`
constructed in other crates therefore satisfies `0 < value ≤ MAX_ERROR_CODE`.
A property that every way of constructing a value establishes and every
operation preserves, so that every value satisfies it, is an **invariant**. The
Lean `structure` below does not record this invariant, so it has to be stated
and proved.

## The generated definitions

* The constant becomes a definition of type `Std.I32`, the Lean model of the
  signed 32-bit integers, whose value `x.val` is an integer in `ℤ`. It carries
  two attributes. The attribute `irreducible` stops Lean from unfolding it
  automatically. The attribute `global_simps` adds its defining equation
  `MAX_ERROR_CODE = 4095#i32` to the set of simp lemmas `global_simps`, through
  which a proof can still reach the value. The theorem `MAX_ERROR_CODE_val`
  below states the value.
* The Rust `struct` becomes a Lean `structure` with the same field.
* The Rust condition `code <= 0 || code > MAX_ERROR_CODE` becomes two nested
  `if`s, since Rust evaluates `||` from left to right and stops at the first
  true operand.
* The result of `from_code` has two layers. The type
  `core.result.Result ErrorCode Unit` is the Lean model of the Rust type
  `Result<ErrorCode, ()>`, with the constructors `Ok` and `Err`; its values are
  ordinary return values of the program. The outer type `Result` of Aeneas
  records how the execution ended: `ok v` for a normal return, `fail e` for a
  failure such as a panic or an overflow, and `div` for a computation that does
  not terminate. The function `from_code` never fails: for an invalid code it
  returns `ok (core.result.Result.Err ())`.
-/

namespace error_codes

/-- [error_codes::MAX_ERROR_CODE]
    Source: 'error_codes/src/lib.rs', lines 9:0-9:37
    Visibility: public -/
@[global_simps, irreducible] def MAX_ERROR_CODE : Std.I32 := 4095#i32

/-- [error_codes::ErrorCode]
    Source: 'error_codes/src/lib.rs', lines 12:0-14:1
    Visibility: public -/
structure ErrorCode where
  value : Std.I32

/-- [error_codes::{error_codes::ErrorCode}::from_code]:
    Source: 'error_codes/src/lib.rs', lines 18:4-27:5
    Visibility: public -/
def ErrorCode.from_code
  (code : Std.I32) : Result (core.result.Result ErrorCode Unit) := do
  if code <= 0#i32
  then ok (core.result.Result.Err ())
  else
    if code > MAX_ERROR_CODE
    then ok (core.result.Result.Err ())
    else ok (core.result.Result.Ok { value := code })

/-- [error_codes::{error_codes::ErrorCode}::to_code]:
    Source: 'error_codes/src/lib.rs', lines 30:4-32:5
    Visibility: public -/
def ErrorCode.to_code (self : ErrorCode) : Result Std.I32 := do
  ok self.value


----------------------------------------------------------------------------------------------------
-- Specs & Formal verification
----------------------------------------------------------------------------------------------------

/-!
## The value of the constant

The tactic `simp only [global_simps]` uses the equation added by the attribute
`global_simps` to replace `MAX_ERROR_CODE` by `4095#i32`, which leaves the goal
`(4095#i32).val = 4095`. The tactic `scalar_tac` proves it.
-/

theorem MAX_ERROR_CODE_val : MAX_ERROR_CODE.val = 4095 := by
  simp only [global_simps]; scalar_tac

/-!
## The specification of `from_code`

The postcondition is a `match` on the inner result. In the case `Ok ec`, the
code lies between `1` and `MAX_ERROR_CODE`, and `ec` stores it unchanged. In the
case `Err ()`, the code lies outside that range. The function never panics, so
the specification has no precondition.

The proof follows the two `if`s with `split`. In each case, `scalar_tac` proves
the inequalities from the condition of the branch and `hp`, and `rfl` proves
`ec.value = code`.
-/

/-- `from_code` returns `Ok` for the codes in `(0, MAX_ERROR_CODE]` and `Err` for
    the others, and in the case `Ok` the constructed `ErrorCode` stores the
    code unchanged. -/
theorem ErrorCode.from_code.spec (code : Std.I32) :
    ErrorCode.from_code code ⦃ res =>
      match res with
      | core.result.Result.Ok ec =>
        0 < code.val ∧ code.val ≤ MAX_ERROR_CODE.val ∧ ec.value = code
      | core.result.Result.Err () =>
        code.val ≤ 0 ∨ MAX_ERROR_CODE.val < code.val ⦄ := by
  unfold ErrorCode.from_code
  have hp := MAX_ERROR_CODE_val
  split
  · exact Or.inl (by scalar_tac)
  · split
    · exact Or.inr (by scalar_tac)
    · exact ⟨by scalar_tac, by scalar_tac, rfl⟩

/-!
## The specification of `to_code`

The simp lemma `WP.spec_ok` rewrites `ok v ⦃ res => P res ⦄` to `P v`, so
`simp` proves the specification after unfolding `to_code`.
-/

/-- `to_code` always succeeds and returns the code stored in the `ErrorCode`.
    That it inverts a successful `from_code` is `from_code_to_code` below. -/
theorem ErrorCode.to_code.spec (self : ErrorCode) :
    ErrorCode.to_code self ⦃ res => res = self.value ⦄ := by
  simp [ErrorCode.to_code]

/-!
## The invariant

The last theorem combines the two specifications: if `from_code code` returns
`ok (Ok ec)`, then `ec` satisfies the invariant, and `to_code ec` returns
`code`. The proof rewrites the specification of `from_code` with `h` and
`WP.spec_ok`, and `obtain` takes out the three facts of the case `Ok ec`. The
lemma `WP.spec_imp_exists` turns the specification of `to_code` into its
existential form, which gives `hto : ErrorCode.to_code ec = ok y`.
-/

/-- Putting the two specs together: whenever `from_code` succeeds, the
    resulting `ErrorCode` satisfies its invariant (`0 < value ≤
    MAX_ERROR_CODE`) and round-trips through `to_code` back to the original
    code. -/
theorem ErrorCode.from_code_to_code
    (code : Std.I32) (ec : ErrorCode)
    (h : ErrorCode.from_code code = ok (core.result.Result.Ok ec)) :
    0 < ec.value.val ∧ ec.value.val ≤ MAX_ERROR_CODE.val ∧
    ErrorCode.to_code ec = ok code := by
  have hspec := ErrorCode.from_code.spec code
  rw [h, WP.spec_ok] at hspec
  obtain ⟨hpos, hmax, heq⟩ := hspec
  subst heq
  obtain ⟨y, hto, hyeq⟩ := WP.spec_imp_exists (ErrorCode.to_code.spec ec)
  refine ⟨hpos, hmax, ?_⟩
  rw [hto, hyeq]

end error_codes
