-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [error_codes]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace error_codes

/-- [error_codes::MAX_ERROR_CODE]
    Source: 'error_codes/src/lib.rs', lines 5:0-5:37
    Visibility: public -/
@[global_simps, irreducible] def MAX_ERROR_CODE : Std.I32 := 4095#i32

/-- [error_codes::ErrorCode]
    Source: 'error_codes/src/lib.rs', lines 8:0-10:1
    Visibility: public -/
structure ErrorCode where
  value : Std.I32

/-- [error_codes::{error_codes::ErrorCode}::from_code]:
    Source: 'error_codes/src/lib.rs', lines 14:4-23:5
    Visibility: public -/
def ErrorCode.from_code
  (code : Std.I32) : Result (core.result.Result ErrorCode Unit) := do
  if code <= 0#i32
  then ok (core.result.Result.Err ())
  else
    if code > MAX_ERROR_CODE
    then ok (core.result.Result.Err ())
    else ok (core.result.Result.Ok { value := code })

/-- [error_codes::{error_codes::ErrorCode}::to_code]:
    Source: 'error_codes/src/lib.rs', lines 26:4-28:5
    Visibility: public -/
def ErrorCode.to_code (self : ErrorCode) : Result Std.I32 := do
  ok self.value


----------------------------------------------------------------------------------------------------
-- Specs & Formal verification
----------------------------------------------------------------------------------------------------


theorem MAX_ERROR_CODE_val : MAX_ERROR_CODE.val = 4095 := by
  simp only [global_simps]; scalar_tac

/-- `from_code` accepts exactly the codes in `(0, MAX_ERROR_CODE]`, and on
    success the constructed `ErrorCode` stores the raw code unchanged. -/
theorem ErrorCode.from_code.spec (code : Std.I32) :
    ErrorCode.from_code code ⦃ res =>
      match res with
      | core.result.Result.Ok ec =>
        0 < code.val ∧ code.val ≤ MAX_ERROR_CODE.val ∧ ec.value = code
      | core.result.Result.Err () =>
        code.val ≤ 0 ∨ MAX_ERROR_CODE.val < code.val ⦄ := by
  unfold ErrorCode.from_code
  have hp := MAX_ERROR_CODE_val
  split
  · rename_i h
    exact Or.inl (by scalar_tac)
  · rename_i h
    split
    · rename_i h2
      exact Or.inr (by scalar_tac)
    · rename_i h2
      exact ⟨by scalar_tac, by scalar_tac, rfl⟩

/-- `to_code` is the exact inverse of a successful `from_code`: it recovers
    the raw code that was stored. -/
theorem ErrorCode.to_code.spec (self : ErrorCode) :
    ErrorCode.to_code self ⦃ res => res = self.value ⦄ := by
  unfold ErrorCode.to_code
  rw [Aeneas.Std.WP.spec_ok]

/-- Putting the two specs together: whenever `from_code` succeeds, the
    resulting `ErrorCode` satisfies its invariant (`0 < value ≤
    MAX_ERROR_CODE`) and round-trips through `to_code` back to the original
    code. -/
theorem ErrorCode.from_code_to_code
    (code : Std.I32) (ec : ErrorCode)
    (h : ErrorCode.from_code code = ok (core.result.Result.Ok ec)) :
    0 < ec.value.val ∧ ec.value.val ≤ MAX_ERROR_CODE.val ∧
    ErrorCode.to_code ec = ok code := by
  have hspec := ErrorCode.from_code.spec code
  rw [h, Aeneas.Std.WP.spec_ok] at hspec
  obtain ⟨hpos, hmax, heq⟩ := hspec
  obtain ⟨y, hto, hyeq⟩ := Aeneas.Std.WP.spec_imp_exists (ErrorCode.to_code.spec ec)
  refine ⟨by rw [heq]; exact hpos, by rw [heq]; exact hmax, ?_⟩
  rw [hto, hyeq, heq]

end error_codes
