-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [max_array]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace max_array

/-- [max_array::max_element]: loop body 0:
    Source: 'max_array/src/lib.rs', lines 4:4-9:5
    Visibility: public -/
@[rust_loop_body]
def max_element_loop.body
  {N : Std.Usize} (data : Array Std.U8 N) (max : Std.U8) (i : Std.Usize) :
  Result (ControlFlow (Std.U8 × Std.Usize) Std.U8)
  := do
  if i < N
  then
    let i1 ← Array.index_usize data i
    let max1 ← if i1 > max
                 then ok i1
                 else ok max
    let i2 ← i + 1#usize
    ok (cont (max1, i2))
  else ok (done max)

/-- [max_array::max_element]: loop 0:
    Source: 'max_array/src/lib.rs', lines 4:4-9:5
    Visibility: public -/
@[rust_loop]
def max_element_loop
  {N : Std.Usize} (data : Array Std.U8 N) (max : Std.U8) (i : Std.Usize) :
  Result Std.U8
  := do
  loop
    (fun (max1, i1) => max_element_loop.body data max1 i1)
    (max, i)

/-- [max_array::max_element]:
    Source: 'max_array/src/lib.rs', lines 1:0-11:1
    Visibility: public -/
def max_element {N : Std.Usize} (data : Array Std.U8 N) : Result Std.U8 := do
  let max ← Array.index_usize data 0#usize
  max_element_loop data max 1#usize


----------------------------------------------------------------------------------------------------
-- Specs & Formal verification
----------------------------------------------------------------------------------------------------


@[step]
theorem max_element_loop.spec
    {N : Std.Usize} (data : Array Std.U8 N) (max : Std.U8) (i : Std.Usize)
    (hi : i.val ≤ N.val)
    (hmax : ∀ j : Fin N.val, j.val < i.val → data[j] ≤ max) :
    max_element_loop data max i ⦃ res =>
      max ≤ res ∧ ∀ j : Fin N.val, data[j] ≤ res ⦄ := by
  unfold max_element_loop
  apply loop.spec_decr_nat
    (measure := fun (p : Std.U8 × Std.Usize) => N.val - p.2.val)
    (inv := fun (p : Std.U8 × Std.Usize) =>
      i.val ≤ p.2.val ∧ p.2.val ≤ N.val ∧
      max ≤ p.1 ∧
      (∀ j : Fin N.val, j.val < p.2.val → data[j] ≤ p.1))
  · rintro ⟨m, i'⟩ ⟨hii, hi'len, hmm, hbelow⟩
    unfold max_element_loop.body
    step*
    split
    · rename_i hc
      step*
      have hmi1 : m ≤ i1 := by scalar_tac
      have hmax_i1 : max ≤ i1 := le_trans hmm hmi1
      refine ⟨by scalar_tac, by scalar_tac, hmax_i1, ?_, by scalar_tac⟩
      intro j hj
      rcases Nat.lt_or_ge j.val i'.val with hjlt | hjge
      · exact le_trans (hbelow j hjlt) hmi1
      · have heq : j.val = i'.val := by scalar_tac
        have hb : j.val < data.val.length := by scalar_tac
        have hdj : data[j] = i1 := by
          rw [Fin.getElem_fin data j hb, Array.getElem_Nat_eq data j.val (by scalar_tac), i1_post]
          congr 1
        rw [hdj]
    · rename_i hc
      step*
      have hi1m : i1 ≤ m := by scalar_tac
      refine ⟨by scalar_tac, by scalar_tac, hmm, ?_, by scalar_tac⟩
      intro j hj
      rcases Nat.lt_or_ge j.val i'.val with hjlt | hjge
      · exact hbelow j hjlt
      · have heq : j.val = i'.val := by scalar_tac
        have hb : j.val < data.val.length := by scalar_tac
        have hdj : data[j] = i1 := by
          rw [Fin.getElem_fin data j hb, Array.getElem_Nat_eq data j.val (by scalar_tac), i1_post]
          congr 1
        rw [hdj]
        exact hi1m
  · exact ⟨le_refl _, hi, le_refl _, hmax⟩


/-- `max_element` returns a value that is greater than or equal to every
    element of the array. -/
theorem max_element.spec
    {N : Std.Usize} (data : Array Std.U8 N) (hN : 0 < N.val) :
    max_element data ⦃ res => ∀ j : Fin N.val, data[j] ≤ res ⦄ := by
  unfold max_element
  step as ⟨ max, hmax_post ⟩
  have hmax0 : ∀ j : Fin N.val, j.val < (1#usize).val → data[j] ≤ max := by
    intro j hj
    have heq : j.val = 0 := by scalar_tac
    have hjeq : j = ⟨0, hN⟩ := Fin.ext heq
    rw [hjeq, Fin.getElem_fin data ⟨0, hN⟩ (by scalar_tac),
        Array.getElem_Nat_eq data 0 (by scalar_tac), ← hmax_post]
  apply Aeneas.Std.WP.spec_mono
    (max_element_loop.spec data max (1#usize) (by scalar_tac) hmax0)
  intro x hx
  exact hx.2


end max_array
