/-
Copyright (c) 2026 Iulian Simion. All rights reserved.
Released under the 3-Clause BSD License as described in the file LICENSE.
Authors: Iulian Simion, assisted by Claude (Anthropic) and Gemini (Google)
-/
-- THE DEFINITIONS UP TO `Specs & Formal verification` WERE GENERATED BY AENEAS
-- [max_array]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-!
# The maximum of an array

The Rust function computes the largest element of an array of bytes with a
`while` loop:

```rust
pub fn max_element<const N: usize>(data: [u8; N]) -> u8 {
    let mut max: u8 = data[0];
    let mut i: usize = 1;
    while i < N {
        if data[i] > max {
            max = data[i];
        }
        i += 1;
    }
    max
}
```

The length `N` is a parameter of the function, a const generic, and it is the
length in the array type `[u8; N]`. For `N = 0`, the access `data[0]` is outside
the array, and the function panics at run time; since `N` is a parameter, the
compiler cannot reject the access.

## The generated definitions

* The type `Array Std.U8 N`, with `N : Std.Usize`, is the Lean model of
  `[u8; N]`. A term of it is a list of bytes together with a proof that its
  length is `N.val`.
* The access `data[i]` becomes `Array.index_usize data i`, which fails when
  `i` is not less than `N`.
* The loop becomes two definitions. The function `max_element_loop.body`
  performs one iteration. It takes the array `data`, which the loop does not
  modify, and the current values `max` and `i` of the two mutable variables.
  It returns `ok (cont (max1, i2))` to continue with new values, or
  `ok (done max)` to leave the loop with a result; the type `ControlFlow` has
  these two constructors. In `ControlFlow (Std.U8 × Std.Usize) Std.U8`, the first
  argument is the type of the values carried by `cont` and the second the type
  of the result carried by `done`. This is the type `ControlFlow` of Aeneas,
  not its model of the Rust type `core::ops::ControlFlow`, whose constructors
  are `Continue` and `Break`.
* The pair of the current values is the **state** of the loop. The function
  `max_element_loop` turns the body into a function of the state and applies
  the library function `loop` to it. The term `loop body x` evaluates `body x`;
  on `cont x'` it continues with `loop body x'`, on `done y` it returns `ok y`,
  and it fails when `body x` fails. The function `loop` is defined with
  `partial_fixpoint`, which does not require a termination proof, since a Rust
  loop need not terminate: a loop that runs forever has the value `div`. Since
  `div` never satisfies a specification `⦃ ⦄`, proving a specification of a
  loop also proves that the loop terminates.
* Aeneas names the values it introduces by counting, so the same name can mean
  different things. In the body, `i1` is the byte read from the array and the
  index is `i`; in `max_element_loop`, `i1` is the index.
-/

namespace max_array

/-- [max_array::max_element]: loop body 0:
    Source: 'max_array/src/lib.rs', lines 4:4-9:5
    Visibility: public -/
@[rust_loop_body]
def max_element_loop.body
  {N : Std.Usize} (data : Array Std.U8 N) (max : Std.U8) (i : Std.Usize) :
  Result (ControlFlow (Std.U8 × Std.Usize) Std.U8)
  := do
  if i < N
  then
    let i1 ← Array.index_usize data i
    let max1 ← if i1 > max
                 then ok i1
                 else ok max
    let i2 ← i + 1#usize
    ok (cont (max1, i2))
  else ok (done max)

/-- [max_array::max_element]: loop 0:
    Source: 'max_array/src/lib.rs', lines 4:4-9:5
    Visibility: public -/
@[rust_loop]
def max_element_loop
  {N : Std.Usize} (data : Array Std.U8 N) (max : Std.U8) (i : Std.Usize) :
  Result Std.U8
  := do
  loop
    (fun (max1, i1) => max_element_loop.body data max1 i1)
    (max, i)

/-- [max_array::max_element]:
    Source: 'max_array/src/lib.rs', lines 1:0-11:1
    Visibility: public -/
def max_element {N : Std.Usize} (data : Array Std.U8 N) : Result Std.U8 := do
  let max ← Array.index_usize data 0#usize
  max_element_loop data max 1#usize


----------------------------------------------------------------------------------------------------
-- Specs & Formal verification
----------------------------------------------------------------------------------------------------

/-!
## Loop invariants

A statement about a loop is proved with a **loop invariant**, a property of the
state that holds when the loop starts and that every iteration which continues
preserves; the iteration that leaves the loop must establish the postcondition
instead. The library lemma `loop.spec_decr_nat` proves `loop body x ⦃ post ⦄`
from

* an invariant `inv` on states, with `inv x` for the initial state `x`;
* a **measure**, a function from states to `ℕ`;
* a proof that, from every state `s` with `inv s`, the body succeeds and either
  returns `done y` with `post y`, or returns `cont s'` with `inv s'` and a
  measure of `s'` smaller than that of `s`.

There is no infinitely decreasing sequence of natural numbers, so the measure
ensures that `loop body x` is not `div`. The measure and the invariant are given
by name, and the two remaining goals follow the order of the lemma: first the
proof about the body, then `inv x` for the initial state.

For `max_element_loop` started at the state `(max, i)`, the measure of a state
`(m, i')` is the natural number `N.val - i'.val`; the invariant keeps
`i' ≤ N`, so this subtraction in `ℕ` does not truncate. The invariant states
that `i ≤ i' ≤ N`, that `max ≤ m`, and that `m` is at least every element at a
position below `i'`. The loop ends when `¬ (i' < N)`, which together with
`i' ≤ N` gives `i' = N`, so `m` is at least every element of the array.

In the proof, `rintro ⟨m, i'⟩ ⟨hii, hi'len, hmm, hbelow⟩` names the state and
the parts of the invariant. The tactic `step*` applies `step` and `split`
repeatedly: it splits on `i' < N` and closes the branch that leaves the loop.
In the remaining branch, `split` distinguishes whether the new element is larger
than `m`. The hypotheses that `step` introduces for the values it names end with
`_post`, such as `i1_post`. An element is written `data[j]` for a position
`j : Fin N.val`, a natural number below `N.val`. The lemmas `Fin.getElem_fin` of
Lean core and `Array.getElem_Nat_eq` of Aeneas rewrite it to
`data.val[j.val]`, the form in which the specification of `Array.index_usize`
states its result. The fact `hdj` does this once for the position `i'`, before
the case split.

The attribute `@[step]` adds the theorem to the specifications that `step` can
use.
-/

@[step]
theorem max_element_loop.spec
    {N : Std.Usize} (data : Array Std.U8 N) (max : Std.U8) (i : Std.Usize)
    (hi : i.val ≤ N.val)
    (hmax : ∀ j : Fin N.val, j.val < i.val → data[j] ≤ max) :
    max_element_loop data max i ⦃ res =>
      max ≤ res ∧ ∀ j : Fin N.val, data[j] ≤ res ⦄ := by
  unfold max_element_loop
  apply loop.spec_decr_nat
    (measure := fun (p : Std.U8 × Std.Usize) => N.val - p.2.val)
    (inv := fun (p : Std.U8 × Std.Usize) =>
      i.val ≤ p.2.val ∧ p.2.val ≤ N.val ∧
      max ≤ p.1 ∧
      (∀ j : Fin N.val, j.val < p.2.val → data[j] ≤ p.1))
  · rintro ⟨m, i'⟩ ⟨hii, hi'len, hmm, hbelow⟩
    unfold max_element_loop.body
    step*
    have hdj : ∀ j : Fin N.val, j.val = i'.val → data[j] = i1 := by
      intro j heq
      have hb : j.val < data.val.length := by scalar_tac
      rw [Fin.getElem_fin data j hb, Array.getElem_Nat_eq data j.val (by scalar_tac), i1_post]
      simp only [heq]
    split
    · step*
      have hmi1 : m ≤ i1 := by scalar_tac
      have hmax_i1 : max ≤ i1 := le_trans hmm hmi1
      refine ⟨by scalar_tac, by scalar_tac, hmax_i1, ?_, by scalar_tac⟩
      intro j hj
      rcases Nat.lt_or_ge j.val i'.val with hjlt | hjge
      · exact le_trans (hbelow j hjlt) hmi1
      · exact le_of_eq (hdj j (by scalar_tac))
    · step*
      have hi1m : i1 ≤ m := by scalar_tac
      refine ⟨by scalar_tac, by scalar_tac, hmm, ?_, by scalar_tac⟩
      intro j hj
      rcases Nat.lt_or_ge j.val i'.val with hjlt | hjge
      · exact hbelow j hjlt
      · rw [hdj j (by scalar_tac)]
        exact hi1m
  · exact ⟨le_rfl, hi, le_rfl, hmax⟩

/-!
## The specification of `max_element`

The precondition `0 < N.val` excludes the panic at `data[0]`. The proof handles
the access `data[0]` with `step`, proves the hypothesis `hmax` of
`max_element_loop.spec` for the starting index `1`, since the only position
below `1` is `0`, and weakens the specification of the loop with
`WP.spec_mono` to its second part.

The statement corresponds to the upper-bound part of the specification in
`MaxList.lean` of the morning session. The membership part is not stated here,
and without it the specification is weak: a function that always returns `255`
also satisfies it. Only the two parts together determine the maximum.
-/

/-- `max_element` returns a value that is greater than or equal to every
    element of the array; this is only the upper-bound part of a specification
    of the maximum. -/
theorem max_element.spec
    {N : Std.Usize} (data : Array Std.U8 N) (hN : 0 < N.val) :
    max_element data ⦃ res => ∀ j : Fin N.val, data[j] ≤ res ⦄ := by
  unfold max_element
  step as ⟨ max, hmax_post ⟩
  have hmax0 : ∀ j : Fin N.val, j.val < (1#usize).val → data[j] ≤ max := by
    intro j hj
    have heq : j.val = 0 := by scalar_tac
    have hjeq : j = ⟨0, hN⟩ := Fin.ext heq
    rw [hjeq, Fin.getElem_fin data ⟨0, hN⟩ (by scalar_tac),
        Array.getElem_Nat_eq data 0 (by scalar_tac)]
    exact le_of_eq hmax_post.symm
  apply WP.spec_mono
    (max_element_loop.spec data max (1#usize) (by scalar_tac) hmax0)
  intro x hx
  exact hx.2

end max_array
