-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [mersenne31]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace mersenne31

/-- [mersenne31::PRIME]
    Source: 'mersenne31/src/lib.rs', lines 4:0-4:34
    Visibility: public -/
@[global_simps, irreducible] def PRIME : Std.U32 := 2147483647#u32

/-- [mersenne31::M31]
    Source: 'mersenne31/src/lib.rs', lines 6:0-8:1
    Visibility: public -/
structure M31 where
  value : Std.U32

/-- [mersenne31::add_m31]:
    Source: 'mersenne31/src/lib.rs', lines 10:0-19:1
    Visibility: public -/
def add_m31 (a : M31) (b : M31) : Result M31 := do
  let sum ← a.value + b.value
  if sum >= PRIME
  then let sum1 ← sum - PRIME
       ok { value := sum1 }
  else ok { value := sum }


----------------------------------------------------------------------------------------------------
-- Specs & Formal verification
----------------------------------------------------------------------------------------------------


theorem PRIME_val : PRIME.val = 2147483647 := by
  simp only [global_simps]; scalar_tac


/-- `add_m31` correctly computes addition modulo `PRIME`: it succeeds on
    well-formed field elements, the result equals the sum reduced modulo
    `PRIME`, and the result is itself a well-formed field element. -/
theorem add_m31.spec (a b : M31) (ha : a.value.val < PRIME.val) (hb : b.value.val < PRIME.val) :
    add_m31 a b ⦃ res =>
      res.value.val = (a.value.val + b.value.val) % PRIME.val ∧
      res.value.val < PRIME.val ⦄ := by
  unfold add_m31
  have hp := PRIME_val
  step as ⟨ sum, hsum_post ⟩
  split
  · rename_i hge
    step as ⟨ sum1, hsum1_post ⟩
    have h1 : sum1.val = sum.val - PRIME.val := by scalar_tac
    have h2 : sum.val = a.value.val + b.value.val := by scalar_tac
    have h3 : PRIME.val ≤ sum.val := by scalar_tac
    refine ⟨?_, by scalar_tac⟩
    show sum1.val = (a.value.val + b.value.val) % PRIME.val
    rw [h1, h2, ← h2, Nat.mod_eq_sub_mod h3, Nat.mod_eq_of_lt (by scalar_tac)]
  · rename_i hlt
    have h2 : sum.val = a.value.val + b.value.val := by scalar_tac
    refine ⟨?_, by scalar_tac⟩
    change sum.val = (a.value.val + b.value.val) % PRIME.val
    rw [h2, Nat.mod_eq_of_lt (by scalar_tac)]


end mersenne31
