/-
Copyright (c) 2026 Iulian Simion. All rights reserved.
Released under the 3-Clause BSD License as described in the file LICENSE.
Authors: Iulian Simion, assisted by Claude (Anthropic) and Gemini (Google)
-/
-- THE DEFINITIONS UP TO `Specs & Formal verification` WERE GENERATED BY AENEAS
-- [mersenne31]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-!
# Addition modulo a prime

The number `p = 2 ^ 31 - 1 = 2147483647` is prime. A prime of the form
`2 ^ k - 1` is called a **Mersenne prime**. Its exponent `k` is necessarily
prime, since for every divisor `d` of `k` with `1 < d < k`, the number
`2 ^ d - 1` is a factor of `2 ^ k - 1` strictly between `1` and `2 ^ k - 1`.
Here `k = 31`. The numbers `0, 1, …, p - 1` with addition and multiplication
modulo `p` form a field.

The Rust code stores such a number in a `u32` and adds two of them:

```rust
pub const PRIME: u32 = 2147483647;

pub struct M31 {
    pub value: u32,
}

pub fn add_m31(a: M31, b: M31) -> M31 {
    let mut sum = a.value + b.value;
    if sum >= PRIME {
        sum -= PRIME;
    }
    M31 { value: sum }
}
```

If `a.value < p` and `b.value < p`, then `a.value + b.value ≤ 2 * p - 2`, which
is less than `2 ^ 32`, so the addition does not overflow. If the sum is at least
`p`, subtracting `p` once brings it below `p`. The result is then the sum modulo
`p`.

The type `M31` does not enforce `value < p`: the field is public, and any `u32`
can be stored in it. For larger values, the addition can overflow, and the
program panics in a debug build and computes a wrong result in a release build.
The condition `value < p` is therefore a **precondition** of `add_m31`, and the
specification below states it as the hypotheses `ha` and `hb`.

## The generated definitions

The constant and the structure are translated as in `ErrorCodes_verified.lean`.
In `add_m31`, the mutable variable `sum` becomes two names, since Aeneas gives
each new value of a mutable variable its own name: here `sum` for its first
value and `sum1` for its value after `sum -= PRIME`. Both the addition and the
subtraction can fail: the addition on overflow, and the subtraction when the
result would be negative.
-/

namespace mersenne31

/-- [mersenne31::PRIME]
    Source: 'mersenne31/src/lib.rs', lines 4:0-4:34
    Visibility: public -/
@[global_simps, irreducible] def PRIME : Std.U32 := 2147483647#u32

/-- [mersenne31::M31]
    Source: 'mersenne31/src/lib.rs', lines 6:0-8:1
    Visibility: public -/
structure M31 where
  value : Std.U32

/-- [mersenne31::add_m31]:
    Source: 'mersenne31/src/lib.rs', lines 10:0-19:1
    Visibility: public -/
def add_m31 (a : M31) (b : M31) : Result M31 := do
  let sum ← a.value + b.value
  if sum >= PRIME
  then let sum1 ← sum - PRIME
       ok { value := sum1 }
  else ok { value := sum }


----------------------------------------------------------------------------------------------------
-- Specs & Formal verification
----------------------------------------------------------------------------------------------------

/-!
## The value of the constant

The constant `PRIME` is irreducible, so no tactic unfolds it by itself. The
theorem `PRIME_val` states its value once, as `MAX_ERROR_CODE_val` does in
`ErrorCodes_verified.lean`.
-/

theorem PRIME_val : PRIME.val = 2147483647 := by
  simp only [global_simps]; scalar_tac

/-!
## The specification

The preconditions `a.value.val < PRIME.val` and `b.value.val < PRIME.val` state
that both arguments are reduced modulo `p`. Under them, `add_m31` succeeds, its
result is the sum modulo `p`, and the result is again reduced. The last part
follows from the second, since a remainder modulo `p` is less than `p`; it is
stated separately because it is what a caller of `add_m31` needs.

In the proof, `have hp := PRIME_val` brings the value of `PRIME` into the
context. Then `step as ⟨ sum, hsum_post ⟩` handles the addition: it proves the
precondition that excludes overflow from `ha`, `hb` and `hp`, and introduces the
sum with its postcondition. Then `split` distinguishes the two branches of the
`if`. In the first branch, a second `step` handles the subtraction, whose
precondition `PRIME.val ≤ sum.val` follows from the condition of the branch.
The two library lemmas `Nat.mod_eq_sub_mod : a ≥ b → a % b = (a - b) % b` and
`Nat.mod_eq_of_lt : a < b → a % b = a` of Lean core compute the remainders.
-/

/-- `add_m31` correctly computes addition modulo `PRIME`: it succeeds on
    well-formed field elements, the result equals the sum reduced modulo
    `PRIME`, and the result is itself a well-formed field element. -/
theorem add_m31.spec (a b : M31) (ha : a.value.val < PRIME.val) (hb : b.value.val < PRIME.val) :
    add_m31 a b ⦃ res =>
      res.value.val = (a.value.val + b.value.val) % PRIME.val ∧
      res.value.val < PRIME.val ⦄ := by
  unfold add_m31
  have hp := PRIME_val
  step as ⟨ sum, hsum_post ⟩
  have h2 : sum.val = a.value.val + b.value.val := by scalar_tac
  split
  · step as ⟨ sum1, hsum1_post ⟩
    have h1 : sum1.val = sum.val - PRIME.val := by scalar_tac
    have h3 : PRIME.val ≤ sum.val := by scalar_tac
    refine ⟨?_, by scalar_tac⟩
    rw [h1, ← h2, Nat.mod_eq_sub_mod h3, Nat.mod_eq_of_lt (by scalar_tac)]
  · refine ⟨?_, by scalar_tac⟩
    change sum.val = (a.value.val + b.value.val) % PRIME.val
    rw [h2, Nat.mod_eq_of_lt (by scalar_tac)]

end mersenne31
