-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [xor_cipher]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace xor_cipher

/-- [xor_cipher::xor_encrypt]: loop body 0:
    Source: 'xor_cipher/src/lib.rs', lines 17:4-20:5
    Visibility: public -/
@[rust_loop_body]
def xor_encrypt_loop.body
  {N : Std.Usize} (key : Std.U8) (data : Array Std.U8 N) (i : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 N) × Std.Usize) (Array Std.U8 N))
  := do
  if i < N
  then
    let i1 ← Array.index_usize data i
    let i2 ← lift (i1 ^^^ key)
    let a ← Array.update data i i2
    let i3 ← i + 1#usize
    ok (cont (a, i3))
  else ok (done data)

/-- [xor_cipher::xor_encrypt]: loop 0:
    Source: 'xor_cipher/src/lib.rs', lines 17:4-20:5
    Visibility: public -/
@[rust_loop]
def xor_encrypt_loop
  {N : Std.Usize} (data : Array Std.U8 N) (key : Std.U8) (i : Std.Usize) :
  Result (Array Std.U8 N)
  := do
  loop
    (fun (data1, i1) => xor_encrypt_loop.body key data1 i1)
    (data, i)

/-- [xor_cipher::xor_encrypt]:
    Source: 'xor_cipher/src/lib.rs', lines 15:0-22:1
    Visibility: public -/
@[reducible]
def xor_encrypt
  {N : Std.Usize} (data : Array Std.U8 N) (key : Std.U8) :
  Result (Array Std.U8 N)
  := do
  xor_encrypt_loop data key 0#usize


----------------------------------------------------------------------------------------------------
-- Specs & Formal verification
----------------------------------------------------------------------------------------------------


/-- Loop invariant: indices below the starting position `i` are left untouched,
    indices at or above `i` end up xored with `key`. -/
theorem xor_encrypt_loop.spec
    {N : Std.Usize} (key : Std.U8) (data : Array Std.U8 N) (i : Std.Usize)
    (hi : i.val ≤ N.val) :
    ∃ res, xor_encrypt_loop data key i = ok res ∧
      (∀ j : Fin N.val, j.val < i.val → res[j] = data[j]) ∧
      (∀ j : Fin N.val, i.val ≤ j.val → res[j] = data[j] ^^^ key) := by
  apply Aeneas.Std.WP.spec_imp_exists
  unfold xor_encrypt_loop
  apply loop.spec_decr_nat
    (measure := fun (p : Array Std.U8 N × Std.Usize) => N.val - p.2.val)
    (inv := fun (p : Array Std.U8 N × Std.Usize) =>
      i.val ≤ p.2.val ∧ p.2.val ≤ N.val ∧
      (∀ j : Fin N.val, j.val < i.val → p.1[j] = data[j]) ∧
      (∀ j : Fin N.val, i.val ≤ j.val → j.val < p.2.val → p.1[j] = data[j] ^^^ key) ∧
      (∀ j : Fin N.val, p.2.val ≤ j.val → p.1[j] = data[j]))
  · rintro ⟨d, i'⟩ ⟨hii, hi'len, hbelow, hmid, habove⟩
    unfold xor_encrypt_loop.body
    step*
    · refine ⟨?_, ?_, ?_, ?_, ?_, ?_⟩
      · scalar_tac
      · scalar_tac
      · intro j hj
        have hne : i'.val ≠ j.val := by scalar_tac
        have hb : j.val < (d.set i' i2).length := by scalar_tac
        rw [a_post, Fin.getElem_fin (d.set i' i2) j hb,
            Array.getElem_Nat_set_ne d i' j.val i2 (by scalar_tac) hne,
            ← Fin.getElem_fin d j (by scalar_tac)]
        exact hbelow j hj
      · intro j hj1 hj2
        rcases Nat.lt_or_ge j.val i'.val with hjlt | hjge
        · have hne : i'.val ≠ j.val := by scalar_tac
          have hb : j.val < (d.set i' i2).length := by scalar_tac
          rw [a_post, Fin.getElem_fin (d.set i' i2) j hb,
              Array.getElem_Nat_set_ne d i' j.val i2 (by scalar_tac) hne,
              ← Fin.getElem_fin d j (by scalar_tac)]
          exact hmid j hj1 hjlt
        · have heq : i'.val = j.val := by scalar_tac
          have hb : j.val < (d.set i' i2).length := by scalar_tac
          rw [a_post, Fin.getElem_fin (d.set i' i2) j hb,
              Array.getElem_Nat_set_eq d i' j.val i2 (by scalar_tac) heq]
          have hda : d[j] = data[j] := habove j (le_of_eq heq)
          have hi1 : i1 = d[j] := by
            rw [i1_post, Fin.getElem_fin d j (by scalar_tac),
                Array.getElem_Nat_eq d j.val (by scalar_tac)]
            congr 1
          rw [hi1, hda] at i2_post2
          bv_tac 8
      · intro j hj
        have hne : i'.val ≠ j.val := by scalar_tac
        have hb : j.val < (d.set i' i2).length := by scalar_tac
        rw [a_post, Fin.getElem_fin (d.set i' i2) j hb,
            Array.getElem_Nat_set_ne d i' j.val i2 (by scalar_tac) hne,
            ← Fin.getElem_fin d j (by scalar_tac)]
        exact habove j (by scalar_tac)
      · scalar_tac
    · refine ⟨hbelow, ?_⟩
      intro j hj
      have hjN := j.isLt
      exact hmid j hj (by scalar_tac)
  · refine ⟨le_refl _, hi, ?_, ?_, ?_⟩
    · intro j hj; rfl
    · intro j hj1 hj2; exact absurd hj1 (by scalar_tac)
    · intro j hj; rfl


/-- `xor_encrypt` always succeeds and xors every byte with `key`
    (existential form, plays nicely with `progress`). -/
private theorem xor_encrypt.exists_spec
    {N : Std.Usize} (data : Array Std.U8 N) (key : Std.U8) :
    ∃ res, xor_encrypt data key = ok res ∧
      ∀ j : Fin N.val, res[j] = data[j] ^^^ key := by
  obtain ⟨res, hres, _, habove⟩ := xor_encrypt_loop.spec key data 0#usize (by scalar_tac)
  exact ⟨res, hres, fun j => habove j (Nat.zero_le _)⟩


/-- `xor_encrypt` xors every byte with `key`. -/
theorem xor_encrypt.spec
    {N : Std.Usize} (data res : Array Std.U8 N) (key : Std.U8)
    (h : xor_encrypt data key = ok res) :
    ∀ i : Fin N.val, res[i] = data[i] ^^^ key := by
  obtain ⟨res', h', hpost⟩ := xor_encrypt.exists_spec data key
  rw [h] at h'
  injection h' with heq
  subst heq
  exact hpost


/-- Two byte arrays obtained by xor-ing `data` with `key` twice (via two
    intermediate results related by `heq1`/`heq2`) both coincide with `data`. -/
private theorem xor_encrypt.injective_aux
    {N : Std.Usize} (data data1 data2 : Array Std.U8 N) (key : Std.U8)
    (heq1 : ∀ j : Fin N.val, data1[j] = data[j] ^^^ key)
    (heq2 : ∀ j : Fin N.val, data2[j] = data1[j] ^^^ key) :
    data2 = data := by
  apply Subtype.ext
  apply List.ext_getElem (by simp)
  intro n hn1 hn2
  have hjN : n < N.val := by scalar_tac
  have bridge : ∀ (v : Array Std.U8 N) (h : n < v.val.length),
      v.val[n]'h = v[(⟨n, hjN⟩ : Fin N.val)] := by
    intro v h
    rw [← Array.getElem_Nat_eq v n (by scalar_tac), Fin.getElem_fin v ⟨n, hjN⟩ (by scalar_tac)]
  rw [bridge data2 hn1, bridge data hn2, heq2 ⟨n, hjN⟩, heq1 ⟨n, hjN⟩]
  generalize data[(⟨n, hjN⟩ : Fin N.val)] = x
  bv_tac 8


/-- `xor_encrypt` is involutive: encrypting twice with the same key returns
    the original data. -/
-- existential form, plays nicely with `progress`
theorem xor_encrypt_involutive
  {N : Std.Usize} (data : Array Std.U8 N) (key : Std.U8) :
  ∃ data1, xor_encrypt data key = ok data1 ∧ xor_encrypt data1 key = ok data
  := by
  obtain ⟨data1, h1, heq1⟩ := xor_encrypt.exists_spec data key
  obtain ⟨data2, h2, heq2⟩ := xor_encrypt.exists_spec data1 key
  have hdd : data2 = data := xor_encrypt.injective_aux data data1 data2 key heq1 heq2
  exact ⟨data1, h1, hdd ▸ h2⟩


-- hypothesis form, weaker: says nothing if the first call fails
theorem xor_encrypt_involutive'
  {N : Std.Usize} (data data1 : Array Std.U8 N) (key : Std.U8)
  (h : xor_encrypt data key = ok data1) :
  xor_encrypt data1 key = ok data
  := by
  have heq1 : ∀ j : Fin N.val, data1[j] = data[j] ^^^ key := xor_encrypt.spec data data1 key h
  obtain ⟨data2, h2, heq2⟩ := xor_encrypt.exists_spec data1 key
  have hdd : data2 = data := xor_encrypt.injective_aux data data1 data2 key heq1 heq2
  exact hdd ▸ h2


end xor_cipher
