/-
Copyright (c) 2026 Iulian Simion. All rights reserved.
Released under the 3-Clause BSD License as described in the file LICENSE.
Authors: Iulian Simion, assisted by Claude (Anthropic) and Gemini (Google)
-/
-- THE DEFINITIONS UP TO `Specs & Formal verification` WERE GENERATED BY AENEAS
-- [xor_cipher]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-!
# The XOR cipher on an array

The Rust function combines every byte of an array with a key by exclusive or,
the cipher of `XorCipher.lean` of the morning session:

```rust
pub fn xor_encrypt<const N: usize>(mut data: [u8; N], key: u8) -> [u8; N] {
    let mut i: usize = 0;
    while i < N {
        data[i] = data[i] ^ key;
        i += 1;
    }
    data
}
```

Unlike `max_element`, this loop modifies the array.

This cipher is a toy: with a key of one byte, it is broken by trying all 256
keys. What is verified below is that the function computes what it should, not
that the encryption is secure.

## The generated definitions

The loop is translated as in `MaxArray_verified.lean`, with the state
`(data, i)`. The assignment `data[i] = …` becomes `Array.update data i i2`,
which returns a new array equal to `data` except at position `i`, and which
fails when `i` is outside the array. Exclusive or on bytes cannot fail; the
library function `lift`, with `lift x = ok x`, turns its value into a `Result`.
The function `xor_encrypt` only calls the loop, and it carries the attribute
`@[reducible]`, so that tactics such as `step` see through it to the call of
`xor_encrypt_loop`.
-/

namespace xor_cipher

/-- [xor_cipher::xor_encrypt]: loop body 0:
    Source: 'xor_cipher/src/lib.rs', lines 3:4-6:5
    Visibility: public -/
@[rust_loop_body]
def xor_encrypt_loop.body
  {N : Std.Usize} (key : Std.U8) (data : Array Std.U8 N) (i : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 N) × Std.Usize) (Array Std.U8 N))
  := do
  if i < N
  then
    let i1 ← Array.index_usize data i
    let i2 ← lift (i1 ^^^ key)
    let a ← Array.update data i i2
    let i3 ← i + 1#usize
    ok (cont (a, i3))
  else ok (done data)

/-- [xor_cipher::xor_encrypt]: loop 0:
    Source: 'xor_cipher/src/lib.rs', lines 3:4-6:5
    Visibility: public -/
@[rust_loop]
def xor_encrypt_loop
  {N : Std.Usize} (data : Array Std.U8 N) (key : Std.U8) (i : Std.Usize) :
  Result (Array Std.U8 N)
  := do
  loop
    (fun (data1, i1) => xor_encrypt_loop.body key data1 i1)
    (data, i)

/-- [xor_cipher::xor_encrypt]:
    Source: 'xor_cipher/src/lib.rs', lines 1:0-8:1
    Visibility: public -/
@[reducible]
def xor_encrypt
  {N : Std.Usize} (data : Array Std.U8 N) (key : Std.U8) :
  Result (Array Std.U8 N)
  := do
  xor_encrypt_loop data key 0#usize


----------------------------------------------------------------------------------------------------
-- Specs & Formal verification
----------------------------------------------------------------------------------------------------

/-!
## The loop invariant

For the loop started at the state `(data, i)`, the invariant of a state
`(d, i')` has five parts. Two bound the index: `i ≤ i'` and `i' ≤ N`. Three
describe the array `d`:

* positions below `i` are unchanged: `d[j] = data[j]`;
* positions from `i` up to but not including `i'` are encrypted:
  `d[j] = data[j] ^^^ key`;
* positions from `i'` on are unchanged.

The measure is the natural number `N.val - i'.val`, a subtraction in `ℕ`, not
the subtraction of `Usize` of the generated code, which can fail. One iteration
encrypts position `i'`, so each part of the invariant is preserved. When the
loop ends, the test gives `N ≤ i'`, which together with `i' ≤ N` gives `i' = N`.
The encrypted positions are then all positions from `i` on, which is the
postcondition.

In the proof, `step` introduces the result `a` of `Array.update` with
`a_post : a = d.set i' i2`, since the specification `Array.update_spec` states
that, for a position `i'` inside the array, `Array.update d i' i2` succeeds with
`d.set i' i2`. The library lemmas `Array.getElem_Nat_set_ne` and
`Array.getElem_Nat_set_eq` give the elements of `d.set i' i2` at a position
different from `i'` and at `i'`; the fact `hset` applies the first of them once
for all positions. The tactic `bv_tac n` translates the goal into a statement
about bit vectors of width `n` and calls `bv_decide`; here the values are bytes,
so `n = 8`.
-/

/-- Specification of the loop: when it ends, the positions below the starting
    position `i` are unchanged, and the positions from `i` on are combined with
    `key`. The loop invariant is the argument `inv` in the proof. -/
@[step]
theorem xor_encrypt_loop.spec
    {N : Std.Usize} (key : Std.U8) (data : Array Std.U8 N) (i : Std.Usize)
    (hi : i.val ≤ N.val) :
    xor_encrypt_loop data key i ⦃ res =>
      (∀ j : Fin N.val, j.val < i.val → res[j] = data[j]) ∧
      (∀ j : Fin N.val, i.val ≤ j.val → res[j] = data[j] ^^^ key) ⦄ := by
  unfold xor_encrypt_loop
  apply loop.spec_decr_nat
    (measure := fun (p : Array Std.U8 N × Std.Usize) => N.val - p.2.val)
    (inv := fun (p : Array Std.U8 N × Std.Usize) =>
      i.val ≤ p.2.val ∧ p.2.val ≤ N.val ∧
      (∀ j : Fin N.val, j.val < i.val → p.1[j] = data[j]) ∧
      (∀ j : Fin N.val, i.val ≤ j.val → j.val < p.2.val → p.1[j] = data[j] ^^^ key) ∧
      (∀ j : Fin N.val, p.2.val ≤ j.val → p.1[j] = data[j]))
  · rintro ⟨d, i'⟩ ⟨hii, hi'len, hbelow, hmid, habove⟩
    unfold xor_encrypt_loop.body
    step*
    · have hset : ∀ j : Fin N.val, i'.val ≠ j.val → a[j] = d[j] := by
        intro j hne
        have hb : j.val < (d.set i' i2).length := by scalar_tac
        rw [a_post, Fin.getElem_fin (d.set i' i2) j hb,
            Array.getElem_Nat_set_ne d i' j.val i2 (by scalar_tac) hne,
            ← Fin.getElem_fin d j (by scalar_tac)]
      refine ⟨?_, ?_, ?_, ?_, ?_, ?_⟩
      · -- `i ≤ i3`
        scalar_tac
      · -- `i3 ≤ N`
        scalar_tac
      · -- positions below `i` are unchanged
        intro j hj
        rw [hset j (by scalar_tac)]
        exact hbelow j hj
      · -- positions from `i` up to `i3` are encrypted
        intro j hj1 hj2
        rcases Nat.lt_or_ge j.val i'.val with hjlt | hjge
        · rw [hset j (by scalar_tac)]
          exact hmid j hj1 hjlt
        · have heq : i'.val = j.val := by scalar_tac
          have hb : j.val < (d.set i' i2).length := by scalar_tac
          rw [a_post, Fin.getElem_fin (d.set i' i2) j hb,
              Array.getElem_Nat_set_eq d i' j.val i2 (by scalar_tac) heq]
          have hda : d[j] = data[j] := habove j (le_of_eq heq)
          have hi1 : i1 = d[j] := by
            rw [i1_post, Fin.getElem_fin d j (by scalar_tac),
                Array.getElem_Nat_eq d j.val (by scalar_tac)]
            congr 1
          rw [hi1, hda] at i2_post2
          bv_tac 8
      · -- positions from `i3` on are unchanged
        intro j hj
        rw [hset j (by scalar_tac)]
        exact habove j (by scalar_tac)
      · -- the measure decreases
        scalar_tac
    · refine ⟨hbelow, ?_⟩
      intro j hj
      exact hmid j hj (by scalar_tac)
  · refine ⟨le_rfl, hi, ?_, ?_, ?_⟩
    · intro j hj; rfl
    · -- the interval of positions from `i` up to `i` is empty
      intro j hj1 hj2
      exfalso
      scalar_tac
    · intro j hj; rfl

/-!
## The specification of `xor_encrypt`

The function starts the loop at position `0`, so every position is encrypted.
The tactic `step` uses the specification of the loop, which is tagged `@[step]`.
Its precondition `i ≤ N` holds for `i = 0`, so the specification of
`xor_encrypt` has no precondition: the function terminates without failure for
every input. The postcondition of `xor_encrypt.spec` is quantified over the
position, and `step` introduces that position under a name that cannot be used;
`rename_i j` gives it the name `j`.
-/

/-- `xor_encrypt` xors every byte with `key`. -/
theorem xor_encrypt.spec {N : Std.Usize} (data : Array Std.U8 N) (key : Std.U8) :
    xor_encrypt data key ⦃ res => ∀ i : Fin N.val, res[i] = data[i] ^^^ key ⦄
    := by
  unfold xor_encrypt
  step as ⟨ res, hbelow, habove ⟩
  rename_i j
  exact habove j (Nat.zero_le _)

/-!
## Encrypting twice

Two arrays of the type `Array Std.U8 N` are equal when they have the same
element at every position: an `Array` is a list together with a proof that its
length is `N.val`, so the lengths agree. The auxiliary theorem below proves
`data2 = data` in this way. `Subtype.ext` reduces the equation of arrays to an
equation of their lists, and `List.ext_getElem` reduces it to the equation of
their lengths, which `simp` proves, and an equation at every position `n`. The
fact `bridge`, which holds by definition, rewrites the element at `n` of the
list into the element of the array. Finally, `generalize` replaces this element
by a variable `x`, and `bv_tac 8` proves `(x ^^^ key) ^^^ key = x`; without
`generalize`, `bv_tac` cannot handle the element of the array and fails.
-/

/-- If `data1` is `data` combined with `key` at every position, and `data2` is
    `data1` combined with `key` at every position, then `data2 = data`. -/
private theorem xor_encrypt.involutive_aux
    {N : Std.Usize} (data data1 data2 : Array Std.U8 N) (key : Std.U8)
    (heq1 : ∀ j : Fin N.val, data1[j] = data[j] ^^^ key)
    (heq2 : ∀ j : Fin N.val, data2[j] = data1[j] ^^^ key) :
    data2 = data := by
  apply Subtype.ext
  apply List.ext_getElem (by simp)
  intro n hn1 hn2
  have hjN : n < N.val := by scalar_tac
  have bridge : ∀ (v : Array Std.U8 N) (h : n < v.val.length),
      v.val[n]'h = v[(⟨n, hjN⟩ : Fin N.val)] := fun _ _ => rfl
  rw [bridge data2 hn1, bridge data hn2, heq2 ⟨n, hjN⟩, heq1 ⟨n, hjN⟩]
  generalize data[(⟨n, hjN⟩ : Fin N.val)] = x
  bv_tac 8

/-!
The round-trip property is stated in two forms. The existential form states
that the first encryption succeeds with some `data1`, and that encrypting
`data1` succeeds with `data`. The hypothesis form assumes that the first call
returns `ok data1`. As formulas, it is weaker, since it states nothing when the
first call fails. Since `xor_encrypt.spec` has no precondition, the first call
always succeeds, and here the two forms give the same information.
-/

/-- Encrypting twice with the same key returns the original data. -/
theorem xor_encrypt_involutive
  {N : Std.Usize} (data : Array Std.U8 N) (key : Std.U8) :
  ∃ data1, xor_encrypt data key = ok data1 ∧ xor_encrypt data1 key = ok data
  := by
  obtain ⟨data1, h1, heq1⟩ := WP.spec_imp_exists (xor_encrypt.spec data key)
  obtain ⟨data2, h2, heq2⟩ := WP.spec_imp_exists (xor_encrypt.spec data1 key)
  have hdd : data2 = data := xor_encrypt.involutive_aux data data1 data2 key heq1 heq2
  rw [hdd] at h2
  exact ⟨data1, h1, h2⟩

/-- Hypothesis form: if the first encryption returns `data1`, then encrypting
    `data1` returns the original data. -/
theorem xor_encrypt_involutive'
  {N : Std.Usize} (data data1 : Array Std.U8 N) (key : Std.U8)
  (h : xor_encrypt data key = ok data1) :
  xor_encrypt data1 key = ok data
  := by
  have heq1 : ∀ j : Fin N.val, data1[j] = data[j] ^^^ key := by
    have hspec := xor_encrypt.spec data key
    rw [h, WP.spec_ok] at hspec
    exact hspec
  obtain ⟨data2, h2, heq2⟩ := WP.spec_imp_exists (xor_encrypt.spec data1 key)
  have hdd : data2 = data := xor_encrypt.involutive_aux data data1 data2 key heq1 heq2
  rw [hdd] at h2
  exact h2

end xor_cipher
