-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [add_ten]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace add_ten

/-- [add_ten::add_ten]:
    Source: 'add_ten/src/lib.rs', lines 1:0-3:1
    Visibility: public -/
def add_ten (x : Std.U32) : Result Std.U32 := do
  x + 10#u32



theorem add_ten_correct (x : Std.U32) (h : x.val + 10 ≤ Std.U32.max) :
  ∃ y, add_ten x = ok y ∧ y.val = x.val + 10 := by
  -- Proof goes here
  sorry

end add_ten
