-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [enums]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace enums

/-- [enums::Light]
    Source: 'enums/src/lib.rs', lines 1:0-1:37
    Visibility: public -/
@[discriminant isize]
inductive Light where
| Red : Light
| Green : Light
| Yellow : Light

/-- [enums::next_light]:
    Source: 'enums/src/lib.rs', lines 3:0-9:1
    Visibility: public -/
def next_light (current : Light) : Result Light := do
  match current with
  | Light.Red => ok Light.Green
  | Light.Green => ok Light.Yellow
  | Light.Yellow => ok Light.Red

end enums
