-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [linux_kernel]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace linux_kernel

/-- [linux_kernel::MAX_ERROR_CODE]
    Source: 'linux_kernel/src/lib.rs', lines 2:0-2:37
    Visibility: public -/
@[global_simps, irreducible] def MAX_ERROR_CODE : Std.I32 := 4095#i32

/-- [linux_kernel::ErrorCode]
    Source: 'linux_kernel/src/lib.rs', lines 5:0-7:1
    Visibility: public -/
structure ErrorCode where
  value : Std.I32

/-- [linux_kernel::{linux_kernel::ErrorCode}::from_code]:
    Source: 'linux_kernel/src/lib.rs', lines 11:4-20:5
    Visibility: public -/
def ErrorCode.from_code
  (code : Std.I32) : Result (core.result.Result ErrorCode Unit) := do
  if code <= 0#i32
  then ok (core.result.Result.Err ())
  else
    if code > MAX_ERROR_CODE
    then ok (core.result.Result.Err ())
    else ok (core.result.Result.Ok { value := code })

/-- [linux_kernel::{linux_kernel::ErrorCode}::to_code]:
    Source: 'linux_kernel/src/lib.rs', lines 23:4-25:5
    Visibility: public -/
def ErrorCode.to_code (self : ErrorCode) : Result Std.I32 := do
  ok self.value

end linux_kernel
