-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [max_iter]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace max_iter

/-- [max_iter::find_max]: loop body 0:
    Source: 'max_iter/src/lib.rs', lines 8:4-12:5
    Visibility: public -/
@[rust_loop_body]
def find_max_loop.body
  (arr : Slice Std.I32) (iter : core.ops.range.Range Std.Usize)
  (max_val : Std.I32) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × Std.I32) Std.I32)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done max_val)
  | some i =>
    let i1 ← Slice.index_usize arr i
    if i1 > max_val
    then ok (cont (iter1, i1))
    else ok (cont (iter1, max_val))

/-- [max_iter::find_max]: loop 0:
    Source: 'max_iter/src/lib.rs', lines 8:4-12:5
    Visibility: public -/
@[rust_loop]
def find_max_loop
  (iter : core.ops.range.Range Std.Usize) (arr : Slice Std.I32)
  (max_val : Std.I32) :
  Result Std.I32
  := do
  loop
    (fun (iter1, max_val1) => find_max_loop.body arr iter1 max_val1)
    (iter, max_val)

/-- [max_iter::find_max]:
    Source: 'max_iter/src/lib.rs', lines 1:0-15:1
    Visibility: public -/
def find_max (arr : Slice Std.I32) : Result (Option Std.I32) := do
  let b ← core.slice.Slice.is_empty arr
  if b
  then ok none
  else
    let max_val ← Slice.index_usize arr 0#usize
    let i := Slice.len arr
    let max_val1 ←
      find_max_loop { start := 1#usize, «end» := i } arr max_val
    ok (some max_val1)

end max_iter
