-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [max_rec]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace max_rec

/-- [max_rec::find_max_rec]:
    Source: 'max_rec/src/lib.rs', lines 10:0-17:1 -/
def find_max_rec
  (arr : Slice Std.I32) (i : Std.Usize) (current_max : Std.I32) :
  Result Std.I32
  := do
  let i1 := Slice.len arr
  if i >= i1
  then ok current_max
  else
    let i2 ← Slice.index_usize arr i
    let next_max ← if i2 > current_max
                     then ok i2
                     else ok current_max
    let i3 ← i + 1#usize
    find_max_rec arr i3 next_max
partial_fixpoint

/-- [max_rec::find_max]:
    Source: 'max_rec/src/lib.rs', lines 1:0-7:1
    Visibility: public -/
def find_max (arr : Slice Std.I32) : Result (Option Std.I32) := do
  let b ← core.slice.Slice.is_empty arr
  if b
  then ok none
  else
    let i ← Slice.index_usize arr 0#usize
    let i1 ← find_max_rec arr 1#usize i
    ok (some i1)

end max_rec
