-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [mersenne31]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace mersenne31

/-- [mersenne31::PRIME]
    Source: 'mersenne31/src/lib.rs', lines 4:0-4:34
    Visibility: public -/
@[global_simps, irreducible] def PRIME : Std.U32 := 2147483647#u32

/-- [mersenne31::M31]
    Source: 'mersenne31/src/lib.rs', lines 6:0-8:1
    Visibility: public -/
structure M31 where
  value : Std.U32

/-- [mersenne31::add_m31]:
    Source: 'mersenne31/src/lib.rs', lines 10:0-19:1
    Visibility: public -/
def add_m31 (a : M31) (b : M31) : Result M31 := do
  let sum ← a.value + b.value
  if sum >= PRIME
  then let sum1 ← sum - PRIME
       ok { value := sum1 }
  else ok { value := sum }

end mersenne31
