-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [mut_borrows]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace mut_borrows

/-- [mut_borrows::increment]:
    Source: 'mut_borrows/src/lib.rs', lines 1:0-3:1
    Visibility: public -/
def increment (x : Std.U32) : Result Std.U32 := do
  x + 1#u32

end mut_borrows
